"""GitHub export — push a built app to a new repository.

Initializes a git repo in the workspace, writes a safe `.gitignore` (so secrets and
local DBs never get pushed), commits, and — if the authenticated `gh` CLI is
present — creates a new GitHub repo and pushes, returning the repo URL. Without
`gh` it still commits locally and returns the exact commands to create + push.

Stdlib only; the actual repo creation uses the user's authenticated `gh` on their
machine. The deterministic parts (gitignore, command building, URL parse) are tested.
"""

from __future__ import annotations

import os
import re
import shutil

_IDENT = ['-c', 'user.email=agent1-harness@local', '-c', 'user.name=Agent1-Harness']
_GITIGNORE = "\n".join([
    "# Generated by Agent1-Harness export",
    ".env", ".env.*", "!.env.example",
    "node_modules/", "__pycache__/", "*.pyc",
    "*.db", "*.db-wal", "*.db-shm", "*.sqlite*",
    ".deploys.json", ".deploy-settings.json", ".previews.json",
    ".studio/", ".venv/", "venv/", "dist/", "build/", ".DS_Store", "",
])
_URL_RE = re.compile(r"https://github\.com/[^\s'\"]+")


def slug(name: str) -> str:
    s = "".join(c if (c.isalnum() or c in "-_.") else "-" for c in (name or "app").lower())
    return s.strip("-._") or "app"


def git_available(which=shutil.which) -> bool:
    return bool(which("git"))


def gh_available(which=shutil.which) -> bool:
    return bool(which("gh"))


def ensure_gitignore(workspace: str) -> bool:
    path = os.path.join(workspace, ".gitignore")
    if os.path.exists(path):
        return False
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(_GITIGNORE)
    return True


def push_commands(name: str, *, private: bool = True) -> list[str]:
    vis = "--private" if private else "--public"
    s = slug(name)
    return [
        f"gh repo create {s} {vis} --source=. --remote=origin --push",
        "# …or without gh:",
        f"git remote add origin https://github.com/<your-username>/{s}.git",
        "git push -u origin main",
    ]


def extract_repo_url(output: str) -> str:
    m = _URL_RE.search(output or "")
    return m.group(0).rstrip("/.").removesuffix(".git") if m else ""


def export(workspace: str, name: str, *, private: bool = True, ci: bool = True,
           runner=None) -> dict:
    """Init + commit the workspace and (if gh is present) create the repo + push.
    With `ci`, also add a stack-aware GitHub Actions workflow so the repo is green."""
    if not git_available():
        return {"ok": False, "ready": False, "reason": "git not found — install git, then:",
                "commands": push_commands(name, private=private)}
    ensure_gitignore(workspace)
    if ci:
        from harness import ci as ci_mod
        ci_mod.write_workflow(workspace)
    if runner is None:
        from harness.sandbox import HostRunner
        runner = HostRunner()
    steps: list[str] = []

    def run(cmd: str):
        proc = runner.run(cmd, workspace, 180)
        steps.append(f"$ {cmd}\n{((proc.stdout or '') + (proc.stderr or '')).strip()}")
        return proc

    if not os.path.isdir(os.path.join(workspace, ".git")):
        run("git init -b main")
    run("git " + " ".join(_IDENT) + " add -A")
    run("git " + " ".join(_IDENT) +
        ' commit -m "Initial commit from Agent1-Harness" --allow-empty')

    if not gh_available():
        return {"ok": False, "ready": False, "committed": True,
                "reason": "gh CLI not found — create the repo and push:",
                "commands": push_commands(name, private=private), "log": "\n".join(steps)}

    vis = "--private" if private else "--public"
    proc = run(f"gh repo create {slug(name)} {vis} --source=. --remote=origin --push")
    out = (proc.stdout or "") + (proc.stderr or "")
    url = extract_repo_url(out)
    if proc.returncode != 0:
        return {"ok": False, "ready": True, "reason": "gh repo create failed",
                "commands": push_commands(name, private=private), "log": "\n".join(steps)}
    return {"ok": True, "url": url, "log": "\n".join(steps)}
